// lib/meetups.js
export const meetupsData = [
    {
      id: 1,
      host: '까비',
      role: '관장님(?)',
      title: '미셸앙리 VIVID 모다갤러리',
      date: '8월 12일',
      day: '화요일',
      location: '모다갤러리',
      status: '5/5명',
      image: '/images/hosts/까비.jpg',
      remainingSpots: 0,
      isLiked: false
    },
    {
      id: 10,
      host: '아트버스',
      role: '28인승 리무진',
      title: '논산 종학당 + 국립부여박물관 + 정림사지',
      date: '8월 10일',
      day: '일요일',
      location: '부여',
      status: '26/26명',
      image: '/images/hosts/bus.jpg',
      remainingSpots: 0,
      isLiked: true
    },
    {
      id: 2,
      host: '바람은',
      role: '바쁜 직장인',
      title: '백영수 미술관 + 서울시립 사진미술관',
      date: '8월 9일',
      day: '토요일',
      location: '백영수 미술관',
      status: '6/7명',
      image: '/images/hosts/바람은.jpg',
      remainingSpots: 1,
      isLiked: true
    },
    {
      id: 3,
      host: '제이커',
      role: '도록 다수 보유자',
      title: '마르크 샤갈과 샤갈의 후계자 (김인중 신부)',
      date: '7월 28일',
      day: '월요일',
      location: '신논현역 폴바셋',
      status: '4/8명',
      image: '/images/hosts/제이커.jpg',
      remainingSpots: 4,
      isLiked: false
    },
    {
      id: 11,
      host: '아트버스',
      role: '28인승 리무진',
      title: '당진 아미미술관 신리성지',
      date: '8월 15일',
      day: '금요일',
      location: '당진',
      status: '26/26명',
      image: '/images/hosts/bus.jpg',
      remainingSpots: 0,
      isLiked: true
    },
    {
      id: 4,
      host: '꿀물',
      role: '도슨트',
      title: '송은 도슨트 투어 하실래요?',
      date: '7월 31일',
      day: '목요일',
      location: '송은',
      status: '9/10명',
      image: '/images/hosts/꿀물.jpg',
      remainingSpots: 1,
      isLiked: true
    },
    {
      id: 5,
      host: '연지빛',
      role: '미술정보여왕',
      title: '서울대 미술관 함께 가실분',
      date: '7월 24일',
      day: '목요일',
      location: '서울대 미술관',
      status: '4/5명',
      image: '/images/hosts/연지빛.jpg',
      remainingSpots: 1,
      isLiked: false
    },
    {
      id: 6,
      host: '그린이',
      role: '사진 작가',
      title: '국립고궁박물관 다시 살려낸 그림속의 희망',
      date: '7월 17일',
      day: '목요일',
      location: '국립고궁박물관',
      status: '5/8명',
      image: '/images/hosts/그린이.jpg',
      remainingSpots: 3,
      isLiked: false
    },
    {
      id: 7,
      host: '티아라',
      role: '월간미술 20년',
      title: '국립현대미술관 현대미술하이라이트',
      date: '7월 12일',
      day: '토요일',
      location: '국립현대미술관',
      status: '6/8명',
      image: '/images/hosts/티아라.jpg',
      remainingSpots: 2,
      isLiked: true
    },
    {
      id: 8,
      host: '제이커',
      role: '도록 다수 보유자',
      title: '도록번개 호퍼, 앤드류 와이어스, 앨리스 달튼 브라운',
      date: '7월 9일',
      day: '수요일',
      location: '신논현 폴바셋',
      status: '4/8명',
      image: '/images/hosts/제이커.jpg',
      remainingSpots: 4,
      isLiked: false
    },
    {
      id: 12,
      host: '아트버스',
      role: '28인승 리무진',
      title: '청주 국현 + 청주시립',
      date: '8월 23일',
      day: '토요일',
      location: '청주',
      status: '26/26명',
      image: '/images/hosts/bus.jpg',
      remainingSpots: 0,
      isLiked: true
    },
    {
      id: 13,
      host: '아트버스',
      role: '28인승 리무진',
      title: '호암 루이스 부르주아',
      date: '8월 30일',
      day: '일요일',
      location: '용인',
      status: '26/26명',
      image: '/images/hosts/bus.jpg',
      remainingSpots: 0,
      isLiked: true
    }
];